server:
  port: 8888
spring:
  application:
    name: feign-consumer
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

